name: Upload Binaries and Docker Image

on:
  push:
    branches:
      - feat/matrix-build-nopush
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
        arch: [amd64, arm64, arm]
        exclude:
          - {os: "macos-latest", arch: "arm"}

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          submodules: recursive

      - name: Install Cosign
        if: matrix.os == 'ubuntu-18.04' && matrix.arch == 'amd64'
        uses: sigstore/cosign-installer@main

      - name: Simulate Build docker image
        if: matrix.os == 'ubuntu-18.04' && matrix.arch == 'amd64'
        run: |
          echo "Simulate docker build"
          sleep 2

      - name: Simulate Login to DockerHub
        if: matrix.os == 'ubuntu-18.04' && matrix.arch == 'amd64'
        run: |
          echo "Simulate dockerhub connection"
          sleep 2

      - name: Simulate Push to DockerHub (release)
        if: matrix.os == 'ubuntu-18.04' && matrix.arch == 'amd64'
        run: |
          echo "Simulate dockerhub push"
          sleep 2

      - name: Simulate Sign the images with GitHub OIDC
        if: matrix.os == 'ubuntu-18.04' && matrix.arch == 'amd64'
        run: |
          echo "Simulate image signature"
          sleep 2

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: build binaries for Linux/MacOS
        env:
          SEMVER: "v5.5.5"
        run: |
          if [ "$RUNNER_OS" == "Linux" ]
          then
              OS="linux"
              TOFND_PATH="/home/runner/work/tofnd/tofnd/target/release"
          else
              OS="darwin"
              TOFND_PATH="/Users/runner/work/tofnd/tofnd/target/release"
          fi
          ARCH="${{ matrix.arch }}"
          cargo install --locked --path .
          mkdir tofndbin
          mv "$TOFND_PATH/tofnd" "./tofndbin/tofnd-$OS-$ARCH-$SEMVER" 

      - name: Test tofnd version
        working-directory: ./tofndbin
        run: |
          ./tofnd-* --version

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Sign binaries
        working-directory: ./tofndbin
        env:
          SEMVER: "v5.5.5"
        run: |
          if [ "$RUNNER_OS" == "Linux" ]
          then
              OS="linux"
          else
              OS="darwin"
          fi
          ARCH="${{ matrix.arch }}" 
          gpg --armor --detach-sign  tofnd-"$OS"-"$ARCH"-"$SEMVER"
          ls -ltr

      - name: Create zip and sha256 files
        working-directory: ./tofndbin
        run: |
          for i in `ls | grep -v .asc`
          do
            shasum -a 256 $i | awk '{print $1}' > $i.sha256
            zip $i.zip $i
            shasum -a 256 $i.zip | awk '{print $1}' > $i.zip.sha256
          done
          ls -ltr
