name: Upload Binaries and Docker Image


on:
  push:
    branches:
      - feat/matrix-build-nopush

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
        arch: [amd64, arm64, arm]
        exclude:
          - {os: "macos-latest", arch: "arm"}

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Create job 
        run: |
          echo 'end to end job creation without push to dockerhub, upload to release and S3'
