name: Test build matrix

on: 
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: test
        run: echo "pipeline creation"
