name: Test build matrix

on:
  push:
    branches:
      - feat/matrix-build
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
        arch: [amd64, arm64, arm]
        exclude:
          - {os: "macos-latest", arch: "arm"}

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          submodules: recursive

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.CICD_RSA_KEY }}

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: build binaries
        run: |
          if [ "$RUNNER_OS" == "Linux" ]
          then
              OS="linux"
              TOFND_PATH="/home/runner/work/tofnd/tofnd/target"
          else
              OS="darwin"
              TOFND_PATH="/Users/runner/work/tofnd/tofnd/target"
          fi
          ARCH="${{ matrix.arch }}"
          cargo install --locked --path .
          ls -la "$TOFND_PATH"
