name: Test build matrix

on:
  push:
    branches:
      - feat/matrix-build
jobs:
  release:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.CICD_RSA_KEY }}
