name: Test build matrix

on:
  push:
    branches:
      - feat/matrix-build
jobs:
  release:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code and submodule
        run: echo "pipeline creation"
